branches:
  only:
  - master
  - develop

os:
  - linux
  - osx
  - windows

osx_image: xcode12.2

language: shell

jdk:
  - openjdk11

env:
  - GRAALVM_VERSION="20.2.0"
  - JAVA_HOME: /c/jdk

before_install:
  - >
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then 
      choco install jdk8;
      choco install maven;
      export PATH=$PATH:"/c/Program Files/Java/jdk1.8.0_191/bin";
    fi;
  - >
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
      sudo apt install maven;
    fi;
  - >
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then 
      brew install maven;
    fi;

install:
  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]] || [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        curl -LJ "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-java11-$DOWNLOAD_OS_NAME-amd64-$GRAALVM_VERSION.tar.gz" --output graalvm.tar.gz
        tar -vxzf graalvm.tar.gz
    fi;
  - >
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        DOWNLOAD_OS_NAME="windows";
        curl -LJ "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-java11-$DOWNLOAD_OS_NAME-amd64-$GRAALVM_VERSION.zip" --output graalvm.zip;
        sudo apt-get install unzip -y
        unzip graalvm.zip;
    fi;

script:
  - export GRAALVM_HOME="$(pwd)/graalvm-ce-java11-$GRAALVM_VERSION" && if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export GRAALVM_HOME="$GRAALVM_HOME/Contents/Home"; fi
  - mvn clean verify
  - mvn package

after_success:
  - mvn clean test jacoco:report coveralls:report
  - mvn site
