branches:
  only:
  - master
  - develop

os:
  - linux
  - osx
  - windows

osx_image: xcode12.2

language: java

jdk:
  - openjdk11

env:
  - GRAALVM_VERSION="20.2.0"

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then DOWNLOAD_OS_NAME="darwin"; fi
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then DOWNLOAD_OS_NAME="linux"; fi
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then DOWNLOAD_OS_NAME="windows"; fi
    curl -LJ "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-java11-$DOWNLOAD_OS_NAME-amd64-$GRAALVM_VERSION.tar.gz" --output graalvm.tar.gz
    tar -vxzf graalvm.tar.gz

script:
  - export GRAALVM_HOME="$(pwd)/graalvm-ce-java11-$GRAALVM_VERSION" && if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export GRAALVM_HOME="$GRAALVM_HOME/Contents/Home"; fi
  - mvn clean verify
  - mvn package

after_success:
  - mvn clean test jacoco:report coveralls:report
  - mvn site
